var files =
[
    [ "activity.c", "activity_8c.htm", "activity_8c" ],
    [ "activity.h", "activity_8h.htm", "activity_8h" ],
    [ "alarm.c", "alarm_8c.htm", "alarm_8c" ],
    [ "client.c", "client_8c.htm", "client_8c" ],
    [ "client.h", "client_8h.htm", "client_8h" ],
    [ "clock.h", "clock_8h.htm", "clock_8h" ],
    [ "config.h", "config_8h.htm", "config_8h" ],
    [ "debug.h", "debug_8h.htm", "debug_8h" ],
    [ "init.c", "init_8c.htm", "init_8c" ],
    [ "init.h", "init_8h.htm", "init_8h" ],
    [ "logging.c", "logging_8c.htm", "logging_8c" ],
    [ "logging.h", "logging_8h.htm", "logging_8h" ],
    [ "lunaservice_utils.c", "lunaservice__utils_8c.htm", "lunaservice__utils_8c" ],
    [ "lunaservice_utils.h", "lunaservice__utils_8h.htm", "lunaservice__utils_8h" ],
    [ "machine.h", "machine_8h.htm", "machine_8h" ],
    [ "main.c", "main_8c.htm", "main_8c" ],
    [ "main.h", "main_8h.htm", "main_8h" ],
    [ "sawmill_logger.c", "sawmill__logger_8c.htm", "sawmill__logger_8c" ],
    [ "sawmill_logger.h", "sawmill__logger_8h.htm", "sawmill__logger_8h" ],
    [ "shutdown.c", "shutdown_8c.htm", "shutdown_8c" ],
    [ "shutdown.h", "shutdown_8h.htm", "shutdown_8h" ],
    [ "smartsql.c", "smartsql_8c.htm", "smartsql_8c" ],
    [ "smartsql.h", "smartsql_8h.htm", "smartsql_8h" ],
    [ "suspend.c", "suspend_8c.htm", "suspend_8c" ],
    [ "suspend.h", "suspend_8h.htm", "suspend_8h" ],
    [ "suspend_ipc.c", "suspend__ipc_8c.htm", "suspend__ipc_8c" ],
    [ "sysfs.c", "sysfs_8c.htm", "sysfs_8c" ],
    [ "sysfs.h", "sysfs_8h.htm", "sysfs_8h" ],
    [ "timeout_alarm.c", "timeout__alarm_8c.htm", "timeout__alarm_8c" ],
    [ "timeout_alarm.h", "timeout__alarm_8h.htm", "timeout__alarm_8h" ],
    [ "timersource.c", "timersource_8c.htm", "timersource_8c" ],
    [ "timersource.h", "timersource_8h.htm", "timersource_8h" ],
    [ "timesaver.c", "timesaver_8c.htm", "timesaver_8c" ],
    [ "timesaver.h", "timesaver_8h.htm", "timesaver_8h" ],
    [ "wait.h", "wait_8h.htm", "wait_8h" ]
];